### ISSUE TITLE
Unable to play against bots

### ISSUE THREAD

**Issue by Alligooter** [MOj0/LoR-Bot#10]
Hello, I've got the program up and running but just can't seem to find how to solely play against bots? In the instructions it says to run "python LOR_Bot.py noPVP" but I'm unable to find out how.

**Comment by MOj0** [comment]
Hi! Since you got the program up and running, you can simply open the Command Prompt in the directory where you cloned the repository and run: `python LOR_Bot.py noPVP`

**Comment by Alligooter** [comment]
blessed
