### ISSUE TITLE
Unknown mana

### ISSUE THREAD

**Issue by Restland** [MOj0/LoR-Bot#12]
Sometimes the bot is running fine but after 2-3 or even 5 games the cmd is spammed with unknown mana is that something that should happen?

**Comment by MOj0** [comment]
The `unknown mana` is printed whenever bot cannot read the mana (something is hovering over it), but eventually that _something_ should go away and mana can be read again, so it definitely should not spam `unknown mana` indefinitely. Are you running on the correct resolution and in-game video quality settings?

**Comment by Restland** [comment]
Yeah, I am running it at 1920x1080 high graphics 30/60 FPS and 100% scale. It works fine when I run it but after a few games it breaks..

**Comment by MOj0** [comment]
Hm, I cannot think of any reason why it would do that. If you know how exactly to reproduce this issue, please post a comment and I will try to debug it, but I'm afraid I cannot help you with just this information, since it works on my end.

**Comment by Restland** [comment]
instead of getting spammed now after the game ended I got this error 
![image](https://user-images.githubusercontent.com/84740054/189519147-746f06f2-907b-4a65-949d-3f4d04aaec25.png)
thats how many games it played 
![image](https://user-images.githubusercontent.com/84740054/189519156-e772c8ad-64c6-4499-b6ec-55854979e77c.png)

**Comment by MOj0** [comment]
Wait, are you on the latest commit of the `master` branch? The `KeyError` bug should already be fixed. If you are on the latest commit and it still does not work, delete the `card_sets` folder and run the program, it will download all the card data (although it might take a while)

**Comment by Restland** [comment]
I downloaded it 3 days ago so I believe I am will do and update you.

**Comment by Restland** [comment]
> Owner

Just happened again after doing it

**Comment by MOj0** [comment]
Does anything in particular happen when this issue occurs? Is anything covering the mana amount on the right side? Again, I need to be able to reproduce the issue in order to debug it.

**Comment by Restland** [comment]
> Does anything in particular happen when this issue occurs? Is anything covering the mana amount on the right side? Again, I need to be able to reproduce the issue in order to debug it.

![image](https://user-images.githubusercontent.com/84740054/189521397-8d3514a8-ed04-4fab-868f-cc60d3de2fd7.png)
I meant this error not the mana one, and nope nothing was hovering it was just playing after my enemy hit my nexus bot got to this error

**Comment by Restland** [comment]
Sorry that was my bad the error is different now 
![image](https://user-images.githubusercontent.com/84740054/189521975-a0b2f76d-5a3f-4879-9a34-0f0b2153cd16.png)

**Comment by MOj0** [comment]
I just added a workaround for missing cards, since they aren't even on Riot's [website](https://developer.riotgames.com/docs/lor) and are apparently not added to the sets. This should resolve the `KeyError` issue.
