### ISSUE TITLE
Nexus health recognition

### ISSUE THREAD

**Issue by ptx96** [MOj0/LoR-Bot#15]
Hello everybody,
first of all, thanks for creating this piece of code!

I'm having a lot of fun developing new "automated" strategies and decks.

---

I've had a look at the code but I don't see any nexus health acknowledgment function:

this would be very useful to recognize lethal situations in which to try to defend yourself by blocking with all your mobs or to make an open attack / decimate only when strictly necessary;

do you plan to develop this feature?

I'd like to help out but I guess there's screen recognition involved again and I'd need to practice a little :)

**Comment by MOj0** [comment]
Hi there (ciao ragazzo :D)

First of all, as far as screen recognition goes it is very primitive. In the folder `mana_values` are 10 screenshots for each mana value. During the game, bot screenshots area where the mana value is and compares it to each of those screenshots, it then picks the one which matches or none if none of them matched. I've tried different approaches for this (including OCR), but this method seems to be the most robust.
So what you could do is take a screenshot for each health value (19 screenshots for values 1..20) and compare them at each frame, just like that is done with the mana values. You could then take that health value into account in various strategies.

I am actually planning to rework the bot such that it reads values directly from memory and does not rely on screen recognition at all, but I don't have time right now. I would say I will start working on the rework in February next year.
