### ISSUE TITLE
Contributions

### ISSUE THREAD

**Issue by jedrzej-grabski** [MOj0/LoR-Bot#18]
Hey, I just wanted to ask if you are looking for fellow contributors. I find your project incredibly interesting and would love to work on it! 
If yes, feel free to hmu on discord at: Mustasz#1138

**Comment by MOj0** [comment]
Well of course! You can open a PR and I will take a look at it :)
I'm actually planning to do a little rework as I commented here: https://github.com/MOj0/LoR-Bot/issues/15, but that will happen in February.
My discord, if you want to dm me: Mojo#7683
I will close this issue now, gl hf :+1:
