### ISSUE TITLE
Make a suggestion about 'Unknown mana'

### ISSUE THREAD

**Issue by KeKeStar6** [MOj0/LoR-Bot#24]
first of all thanks for the bot.
please add a logic in the 'download_card_sets.py' file.
add '(http://dd.b.pvp.net/latest/set6cde/en_us/data/set6cde-en_us.json)'  to 'card_sets'.
'cde'

**Comment by MOj0** [comment]
Done
https://github.com/MOj0/LoR-Bot/commit/eacd3f07a69e511f02c4b1e5e4442293e91597d1
