### ISSUE TITLE
Can we get sets.json directly?

### ISSUE THREAD

**Issue by Barabama** [MOj0/LoR-Bot#25]
`requests.get("https://dd.b.pvp.net/latest/set1/en_us/data/set1-en_us.json")`

**Comment by MOj0** [comment]
Great suggestion, thanks! Implemented here 0966aa59ee6edd72d30fc372e9040fc8f68cb7b5
This made the download so fast, so we can afford to always delete all the existing card sets and download them anew, everytime the bot is started.
