### ISSUE TITLE
Stuck on Targeted Spell

### ISSUE THREAD

**Issue by gkoi00** [MOj0/LoR-Bot#28]
Hello!

Overall the bot works fine for me, except for when it plays a spell that needs a target (e.g. an ally).
The cursor just sits on the middle of the screen and doesnt choose any target.

**Comment by MOj0** [comment]
Hi, yeah this is a known limitation. This would be quite complex to do, as there are a lot of options when it comes to playing a spell. Namely, can it target allies, can it target enemies, should target alliles/enemies, can it target champions, can it target nexuses, does it have multiple targets, ...
I could implment a basic text semantic algorithm, where it reads the description and based on that it plays a spell. This way it could correctly play any spell in the game, which could be quite useful.
But, I'm working on other projects now and don't really have the time. If you feel like doing it yourself, feel free to open a PR and I'll gladly take a look at it :slightly_smiling_face:

**Comment by gkoi00** [comment]
Oh i didn't realise that was the intended action. I suppose then a deck without spells would make this a true afk farming bot. Meanwhile using the strategies and manually targeting spells will suffice for competitive play.
Seems like an interesting feature to try and implement, and i will keep it in mind.
Thank you so much for your amazing work here!
