### ISSUE TITLE
"Unknown mana..." 

### ISSUE THREAD

**Issue by ipoomzakungi** [MOj0/LoR-Bot#3]
"Unknown mana..." whatever my video resolution setting is

**Comment by MOj0** [comment]
Hmm, that is strange... The image recognition only works on 1920x1080 fullscreen on at least **medium** quality.
To achieve anything else would require a massive overhaul of the current code, since there are too many cases to cover.
But still, don't hesitate to open a PR. 😉

**Comment by ipoomzakungi** [comment]
Now I know the problem
I trying to check the screen size ( self.window_width and self.window_height ) when it running its 1536 , 864 
Why 1536 ? because I scaling size of text,app and other items that  can change in Display setting
so when I change it back into 100% ( not scaling ) your code is working fine
