### ISSUE TITLE
New Endscreen for victories bricks the bot. 

### ISSUE THREAD

**Issue by SteamPunkTeacup** [MOj0/LoR-Bot#32]
The beginning loop now does not exit out of the victory screen for AI battles, since the bot is using preset x,y values it should be an easy fix to add an extra couple of values for the bot to click on when the match ends.

**Comment by MOj0** [comment]
So did Riot change the menus up?
I unfortunately won't have access to a windows PC for a while. If it is just a matter of adding values, that can be done [here](https://github.com/MOj0/LoR-Bot/blob/master/Bot.py#L261). Feel free to open a PR :)

**Comment by nezam7** [comment]
so what are the correct values to be add there? can you update those lines
to be replace with here? Thanks

**Comment by E7t7t7** [comment]
> So did Riot change the menus up? I unfortunately won't have access to a windows PC for a while. If it is just a matter of adding values, that can be done [here](https://github.com/MOj0/LoR-Bot/blob/master/Bot.py#L261). Feel free to open a PR :)

they added another screen after the old ones it just requires you to hit another continue button but for now but gets locked up there unfortunately

**Comment by E7t7t7** [comment]
i sent you a screen shot of the new screen on discord

**Comment by MOj0** [comment]
So the way to do that is pretty straightforward. The game is running at 1920x1080 on fullscreen. You just take a screenshot of the screen, get the x,y location of the button and divide x by 1920 and y by 1080. Now you should get a tuple with values between 0 and 1 (eg. `(0.76, 0.86)`). Now all you have to do is insert that tuple in the `vals_ai` list, in code, which I linked, at the right position, depending on when this buttons occurs in the menu sequence.

**Comment by E7t7t7** [comment]
> So the way to do that is pretty straightforward. The game is running at 1920x1080 on fullscreen. You just take a screenshot of the screen, get the x,y location of the button and divide x by 1920 and y by 1080. Now you should get a tuple with values between 0 and 1 (eg. `(0.76, 0.86)`). Now all you have to do is insert that tuple in the `vals_ai` list, in code, which I linked, at the right position, depending on when this buttons occurs in the menu sequence.

not home atm but got this in teamview for you. dead center of new button is this

Screen:	1414, 995
Window:	1414, 995
Client:	1414, 995 (default)
Color:	C5B8A7 (Red=C5 Green=B8 Blue=A7)

**Comment by E7t7t7** [comment]
(0.73645, 0.92129)

thats what im seeing on my end

**Comment by E7t7t7** [comment]
i submitted the PR adding that xy do i have to do a pr for a line other than 261?

**Comment by MOj0** [comment]
There are no PRs open atm.
The way to test if it works, is to simply run a game. If it clicks through the menus correctly then it works and we can merge the PR.

**Comment by E7t7t7** [comment]
> There are no PRs open atm. The way to test if it works, is to simply run a game. If it clicks through the menus correctly then it works and we can merge the PR.

i did the req again let me know if i did that correct

**Comment by E7t7t7** [comment]
the pr diddnt fix it any other lines? i notice that line has to do with deck selection rather than end screen is that something to do with it

**Comment by E7t7t7** [comment]
brother you there?

**Comment by hoangbk009** [comment]
![image](https://github.com/MOj0/LoR-Bot/assets/22829982/89f5c6ea-f265-4eff-b55f-f48d71c267ea)
@MOj0 not working when have screen Champion mastery
