### ISSUE TITLE
bot still not working

### ISSUE THREAD

**Issue by E7t7t7** [MOj0/LoR-Bot#34]
the edit to 261 did not fix the issue

**Comment by Shinimate** [comment]
Yea I just tried the fix theres like 3 continue windows I also have an issue with an opponent surrendering

**Comment by E7t7t7** [comment]
> Yea I just tried the fix theres like 3 continue windows I also have an issue with an opponent surrendering

guess now all we can do is wait for OP to return let me know if you find a solution

**Comment by bomoy** [comment]
Hello, you can solve your problem by changing the continue_and_replay function like this :
```
def continue_and_replay(self):
        sleep(4)
        continue_btn_pos = (self.window_x + 0.66 * self.window_width, self.window_y + self.window_height * 0.90)
        second_continue_btn_pos = (self.window_x + 0.73854 * self.window_width, self.window_y + self.window_height * 0.92222)
        for _ in range(16):
            self.mouse_handler.click(continue_btn_pos)
            self.mouse_handler.click(second_continue_btn_pos)
            sleep(1.5)
        sleep(1)
```

The line 261 is used when choosing a deck, it's at the beginning on the game, not at the end

**Comment by bomoy** [comment]
It's not perfect, it's doing the same thing multiple time, i'm trying to change it and I will raise a PR in a few minutes

**Comment by bomoy** [comment]
PR raised :)
https://github.com/MOj0/LoR-Bot/pull/37
