### ISSUE TITLE
ModuleNotFoundError: No module named 'cv2'

### ISSUE THREAD

**Issue by Shinimate** [MOj0/LoR-Bot#36]
I'm now getting this issue any help?

**Comment by MOj0** [comment]
Try running `pip install -r requirements.txt`.
Also I suggest reading the whole [readme](https://github.com/MOj0/LoR-Bot#prerequisites) :)

**Comment by Shinimate** [comment]
Thanks I'm oblivious as hell I got it working but I think theres an issue with the cursor script they mustve implemented a new window after you finish a game.

**Comment by E7t7t7** [comment]
> Thanks I'm oblivious as hell I got it working but I think theres an issue with the cursor script they mustve implemented a new window after you finish a game.

ey absolutely did

**Comment by Shinimate** [comment]
> > Thanks I'm oblivious as hell I got it working but I think theres an issue with the cursor script they mustve implemented a new window after you finish a game.
> 
> ey absolutely did

Any updates I tried adding the cursor coord to line 261 but doesnt work for me
