### ISSUE TITLE
Matchmaking failures and disconnects

### ISSUE THREAD

**Issue by ERROREND** [MOj0/LoR-Bot#8]
Bot get stuck after matchmaking failures and disconnects. 
![image](https://user-images.githubusercontent.com/19989840/181571773-465a8d41-a179-4f96-9e95-7cade7cd5b3e.png)

**Comment by MOj0** [comment]
Should be [fixed](https://github.com/MOj0/LoR-Bot/commit/ab3d6fd2a56e4ef633b458f7b047bb93a7bb3234) now, ty :)

**Comment by ERROREND** [comment]
Most welcome.  Also when the reconnecting button is shown,  it gets stuck in game.
![image](https://user-images.githubusercontent.com/19989840/181671499-9a127d55-f709-440f-9b71-998ad7b797a1.png)
